### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-horriblesubs-addon#1]
On android devices it always throws `Error retrieving information about on this` when any anime is selected. now.sh error log is empty so this should be investigated locally ASAP.

**Comment by sleeyax** [comment]
Looking for hours but there's literally no reason it doesn't work on android. There are no errors on my side, the response is properly formatted, I strictly follow the stremio-addon-sdk & compared to other addons I don't see that I'm doing anything unusual. I will continue to compare my code to similar addons to find something that I'm missing or isn't properly documented in the stremio-addon-sdk but I'm starting to think it's a bug within the android app itself.

**Comment by BoredLama** [comment]
Hi, thought i'd lend you some help.

As far as i can see, you set videos like this:
<img width="420" alt="Screen Shot 2019-05-23 at 10 06 57" src="https://user-images.githubusercontent.com/43473329/58232711-eb451f00-7d42-11e9-8d68-735ee071c41a.png">

and your stream responses are like this:
<img width="483" alt="Screen Shot 2019-05-23 at 10 03 29" src="https://user-images.githubusercontent.com/43473329/58232722-f1d39680-7d42-11e9-8d48-c3d53945eae5.png">

A typical link to the streaming page of Mushishi looks like:
```
http://app.strem.io/shell-v4.4/#/detail/series/horrible_aHR0cHM6Ly9ob3JyaWJsZXN1YnMuaW5mby9zaG93cy9tdXNoaXNoaS10b2t1YmV0c3UtaGVuLWhpaGFtdWthZ2U=/horrible_316_01
```

Here's my theory:
I think the android app doesn't respect video id, a link to the streams (of season 1, episode 1), if you don't set video id, typically looks like:
```
http://app.strem.io/shell-v4.4/#/detail/series/horrible_aHR0cHM6Ly9ob3JyaWJsZXN1YnMuaW5mby9zaG93cy9tdXNoaXNoaS10b2t1YmV0c3UtaGVuLWhpaGFtdWthZ2U=/horrible_aHR0cHM6Ly9ob3JyaWJsZXN1YnMuaW5mby9zaG93cy9tdXNoaXNoaS10b2t1YmV0c3UtaGVuLWhpaGFtdWthZ2U=:1:1
```

(notice the :1:1 at the end, specifying first the season, then the episode)

I think if you remove the video id (from the meta response), and try supporting id's like: `horrible_aHR0cHM6Ly9ob3JyaWJsZXN1YnMuaW5mby9zaG93cy9tdXNoaXNoaS10b2t1YmV0c3UtaGVuLWhpaGFtdWthZ2U=:1:1` in the streams handler, it might work on android too

**Comment by sleeyax** [comment]
I finally fixed it by following the `id:season:episode` convention AND making the `id` of the  `meta preview object` the same as the `id` of the `meta object` response (which is what mainly caused this issue, because only applying the `:` convention doesn't work, I tried yesterday). 

Feels bad this isn't clearly mentioned in the stremio docs, but thanks for your help - I really appreciate it.
