### ISSUE TITLE
Custom domain, cloudflare caching

### ISSUE THREAD

**Issue by BoredLama** [sleeyax/stremio-horriblesubs-addon#2]
There is a guide here:
https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deploying/now.md

Explaining how to set up a custom domain and cloudflare caching on now.sh (for free). As this add-on uses torrent hashes, you could easily set a 7-24 hour cache for the stream responses (maybe meta too, if the streams requests don't rely on meta being gotten first)

And even a 3-4 day cache for catalog and search responses, for the searching part, you can even respond with `[]` if there are no results, and cache the empty response for a week.

This would drastically reduce the load on your add-on, and whatever api / scraping it is based on, ensuring a longer lasting add-on.

**Comment by sleeyax** [comment]
Just a quick update on this; I have to wait up to 24 hours for the SSL certificates to update. When that happens, everything should be ready for migration to the custom domain with cloudflare caching.
