### ISSUE TITLE
Addon not working. 

### ISSUE THREAD

**Issue by shoubhik7** [sleeyax/stremio-horriblesubs-addon#6]
Addon not working. 
![IMG-20200315-WA0009](https://user-images.githubusercontent.com/61494289/76700821-60724e00-66e1-11ea-8a28-0f5f43226acf.jpg)

**Comment by sleeyax** [comment]
The addon is working as intended. Only the 'Top' category doesn't return anything because it was automatically added by stremio while this addon doesn't use it.

Just choose any other genre than 'Top' (like Latest, season or by letter) and you will get results just fine.
