### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ESM-96** [sleeyax/stremio-horriblesubs-addon#8]
hi,
i comment in the other issue but it's closed so i created a new one.
 "hi, the addon doesn't work...
i add the addon with this URL https://more-milk.xyz/horriblesubs/manifest.json like you said to do.
i can search the anime i want to see but doesn´t work."

sorry for my english..

best regards, 
ESM

**Comment by sleeyax** [comment]
(#7) I'm using a new server to host all addons. I tested all of them locally and it worked, but now it seems they are completely broken in production. 

Tbh, I'm not sure yet what's going on. It could be the unexpected load on the VPS, even though the responses are cached using cloudflare. 

If you use Stremio on your computer, you can install this addon locally as a temporary solution. Install [nodejs](https://nodejs.org/en/), download the source code of this repository, open command prompt/terminal at the location and enter:
```
npm install
node src/server.js
```
An url will pop up that you can copy and paste in the Stremio search bar to install the addon. If you need more help with this let me know.

I feel bad that it doesn't work yet, I truly wish I was finally done with this (now almost 4 days long) nightmare to get it to work. I'll keep trying.

Thanks for letting me know!

**Comment by sleeyax** [comment]
Hi @ESM-96, can you check and let me know if it works for you now?

**Comment by ESM-96** [comment]
hi
it's work!!! great job!
thanks

**Comment by sleeyax** [comment]
Alright that makes me happy :)

I will close this issue now. If you have another problem or question, feel free to open another issue.
